title: GRAPHIC &amp; WEB DESIGNER
url: ''
baseurl: ''
yourname: Brown Smith
location: 'San Francisco , CA'
facebook: 'http://www.facebook.com'
twitter: 'http://www.twitter.com'
linkedin: 'http://www.linkedin.com'
dribbble: 'http://www.dribble.com'
foursquare: 'http://www.foursquare.com'
